Repository ios-study-boost/codingtest, pull requests merged in 2020-09, with the labels that each got.

#5 @jinho Update docstring and upload readme file
  이진호/day01/day01_200831.py
  이진호/day02/day02_200901.py
  이진호/readme.md
Labels: 코테

#7 @devejs Day1, Hash
  신은지/Day1_hash.py
Labels: 코테

#6 Day1-정택현
  정택현/d01_0831.swift
  정택현/d02_0901.swift
Labels: 코테

#11 @jwonylee - 프린터 for Swift
  이지원/0901_42587.swift
Labels: 스위프트, 코테

#13 @Jinho Upload day03 codingTest solution
  이진호/day03/day03_20200902.py
Labels: 코테, 파이썬

#14 @jwonylee - 더 맵게
  이지원/0902_42626.md
  이지원/0902_42626.py
  이지원/README.md
Labels: 코테, 파이썬

#12 @jungin: 0901 codingtest
  이정인/0902.py
Labels: 코테, 파이썬

#19 @jungin : K번째 수
  이정인/08_31 풀이.md
  이정인/0903.py
Labels: 코테, 파이썬

#17 @jwonylee - K번째 수
  이지원/0903_42748.py
  이지원/README.md
Labels: 코테, 파이썬

#20 @jeff-jung-91 upload day04
  정택현/d04_0903.swift
Labels: 스위프트, 코테

#23 @jungin: 모의고사
  이정인/08_31.py
  이정인/0904.py
  이정인/0905.py
Labels: 코테, 파이썬

#21 @Jinho Upload day05 codingTest solution
  이진호/day05/day05_20200904.py
  이진호/readme.md
Labels: 코테, 파이썬

#24 @jwonylee - 모의고사
  이지원/0904_42840.md
  이지원/0904_42840.py
  이지원/0904_42840.swift
  이지원/README.md
Labels: 스위프트, 코테, 파이썬

#29 @Minimoa - 0901 타켓넘버
  이정인/0906.py
Labels: 코테, 파이썬

#28 @jwonylee - 체육복
  이지원/0905_42862.py
  이지원/README.md
Labels: 코테, 파이썬

#31 @jeff-jung-91 - 0907 타켓넘버
  정택현/d07_0907.swift
Labels: 스위프트, 코테

#30 @Jinho - 타겟 넘버
  이진호/day07/day07_200907.py
  이진호/readme.md
Labels: 코테, 파이썬

#34 @jeongin - 0907 입국심사
  이정인/0908.py
Labels: 코테, 파이썬

#36 @jeongin - 0909 가장 먼 노드
  이정인/0909.py
Labels: 코테, 파이썬

#37 @kartmon61 - 가장 먼 노드
  이진호/day09/day09_200909.py
  이진호/readme.md
Labels: 코테, 파이썬

#40 @kartmon61 - 전화번호 목록
  이진호/day10/day10_200910.py
  이진호/readme.md
Labels: 코테, 파이썬

#39 @jwonylee - 0910 전화번호 목록
  이지원/0910_ 42577.py
  이지원/README.md
Labels: 코테, 파이썬

#38 @jeongin - 0910 전화번호 목록
  이정인/0910.py
Labels: 코테, 파이썬

#41 @kartmon61 - 기능 개발
  이진호/day11/day11_200911.py
  이진호/readme.md
Labels: 코테, 파이썬

#44 @kartmon61 - 디스크 컨트롤러
  이진호/day12/day12_200914.py
  이진호/readme.md
Labels: 코테, 파이썬

#43 @jeff-jung-91 - 0914 기능개발
  정택현/d06_0905.swift
  정택현/d11_0911.swift
Labels: 스위프트, 코테

#47 @kartmon61 - 가장 큰 수
  이진호/day13/day13_200915.py
  이진호/readme.md
Labels: 코테, 파이썬

#46 @jeff-jung-91 - 0915 가장 큰 수
  정택현/d13_0915.swift
Labels: 스위프트, 코테

#45 @IMCHO - 0914 디스크 컨트롤러
  조인택/20200914/main.swift
Labels: 스위프트, 코테

#49 @jeff-jung-91 - 소수 찾기
  정택현/d14_0916.swift
Labels: 스위프트, 코테

#50 @IMCHO - 0916 소수 찾기
  조인택/20200916/main.swift
Labels: 스위프트, 코테

#51 @IMCHO - 0917 큰 수 만들기
  조인택/20200917/main.swift
Labels: 스위프트, 코테

#48 @kartmon61 - 소수 찾기
  이진호/day14/day14_200916.py
  이진호/readme.md
Labels: 코테, 파이썬

#56 @IMCHO - 0918 N으로 표현
  조인택/20200918/main.swift
Labels: 스위프트, 코테

#58 @jeongin - 0923 키패드
  이정인/09_23.py
Labels: 코테, 파이썬

#55 @kartmon61 - 멀쩡한 사각형
  이진호/day16/day16_200922.py
  이진호/readme.md
Labels: 코테, 파이썬
